# Generated by Django 4.2.3 on 2023-07-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='name',
            field=models.CharField(help_text='Name of the Snack you want to add', max_length=64),
        ),
    ]
